version: '3.8'
services:
  backend:
    build: ./API
    container_name: spring-postgres
    ports:
      - '8080:8080'
    depends_on:
      - postgres
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432